name: shell command

on:
  - push
env:
  AWS_ACCESS_KEY_ID: ${{  secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{  secrets.AWS_SECRET_ACCESS_KEY }}


jobs:
  terraform-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: Terraform init
        run:  terraform init
      - name: Terraform validate
        run:  terraform validate
      - name: Terraform plan
        run:  terraform plan
      - name: Terraform apply
        run: terraform apply --auto-approve
      - name: Terraform destroy
        run: terraform destroy --auto-approve
      - name: Multi line string
        run:  |
          pwd
          ls -a
          who

